export enum QuestionType {
  UNIQUE_SELECTION = "UNIQUE_SELECTION",
  MULTIPLE_SELECTION = "MULTIPLE_SELECTION",
  TRUE_FALSE = "TRUE_FALSE",
  SHORT_ANSWER = "SHORT_ANSWER",
}

export enum DifficultyLevel {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
}

export enum Topic {
  AI_CONCEPTS = "AI_CONCEPTS",
  MACHINE_LEARNING = "MACHINE_LEARNING",
  DEEP_LEARNING = "DEEP_LEARNING",
  NATURAL_LANGUAGE_PROCESSING = "NATURAL_LANGUAGE_PROCESSING",
  COMPUTER_VISION = "COMPUTER_VISION",
  ROBOTICS = "ROBOTICS",
}